spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dbCiv
    username: root
    password: 123
    driver-class-name: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect


    hibernate:
      ddl-auto: update
server:
  servlet:
    context-path: /api/v1
security:
  basic:
    enabled: false
jwt:
    secret: 984hg493gh0439rthr0429uruj2309yh937gc763fe87t3f89723gf
    lifetime: 10m
