spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dbCiv
    username: root
    password: 123
    driver-class-name: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect

server:
  servlet:
    context-path: /api/v1
security:
  basic:
    enabled: false